nome = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
print('Esse é seu nome em maiúsculo : {} '.format(nome.upper()))
print('Esse é seu nome em minúsculo : {} '.format(nome.lower()))
totC = int(len(nome))
totS = int(nome.count(' '))
print('O total de letras em seu nome é {}'.format(totC - totS))
divnome = nome.split()
print('O seu primeiro nome tem {} letras.'.format(len(divnome[0])))
